[package]
name = "huntnft"
version = "0.1.0"
authors = ["kelvinkirima014 <kelvinkirima2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
